### ISSUE TITLE
Investigation Findings are storing English strings instead of Lookup ID's

### ISSUE THREAD

**Issue by nerdkid93** [OasisHospital/frontend#40]
In app/incident/investigation-findings, the controller is displaying and storing English strings as part of each entry instead of using a key with a lookup that can display multiple languages.

**Comment by nerdkid93** [comment]
```
typeOfPersonInvolved: [
    'Patient',
    'Staff',
    'Visitor'
  ].map(SelectValues.selectValuesMap),

  identityDocumentTypes: [
    'Employee Number',
    'ID Card',
    'Passport',
    'Medical Record Number',
    'Driving License Number',
    'Mobile Number'
  ].map(SelectValues.selectValuesMap),
```

To further explain the issue, instead of storing "Employee Number" in Pouch, we either store an integer or a string to be used to lookup the string to be displayed.

So instead of storing "Employee Number", we store "employeeNumber" and we display "Employee Number" after using conditional logic to determine which idType is being used.

**Comment by jkleinsc** [comment]
@nerdkid93 we can talk about this more in person, but because we are using an object store database (couch/pouch) instead of a relational database, we typically don't use lookup ids and do instead store the actual strings.  This doesn't mean there aren't times where we don't use lookup ids/values, but those relationships are then handled via ember data using hasMany/belongsTo relationships.

**Comment by nerdkid93** [comment]
@jkleinsc The issue I meant to report was that by storing English strings in Pouch, it is significantly more difficult to add i18n support for the module.
